---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: tracklines
  name: soon
  annotations:
    cert-manager.io/cluster-issuer: acme-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: soon
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tracklin.es
        - tracklines.dev
        - www.tracklin.es
        - www.tracklines.dev
      secretName: tracklines-soon-tls
  rules:
    - host: tracklin.es
      http:
        paths:
          - backend:
              service:
                name: soon
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: tracklines.dev
      http:
        paths:
          - backend:
              service:
                name: soon
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: www.tracklin.es
      http:
        paths:
          - backend:
              service:
                name: soon
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: www.tracklines.dev
      http:
          paths:
            - backend:
                service:
                    name: soon
                    port:
                      number: 80
              path: /
              pathType: Prefix
